name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODBhYjVlMDgtNWRiYi00NDRjLTliMTgtODQ2NGM1MjgyMjVmIiwidGVuYW50X2lkIjoiM2I0ODcyYzExMzczYWExMDk5NDdkMzVhY2I2Zjc3NDAzZjM4NmUwODA5MzIwNjhlNjljZjJkYmJjZTczYTg2YyIsImludGVybmFsX3NlY3JldCI6IjcwZmRhMWRkLTc5ZGQtNGFkNy1hNTAwLTQyYTI0Y2M1NGExZSJ9.7cZ9LWAxFG6dBX1FHLjMoatJrBVUEFCl0nu-NXu21cc"
Jwt_Secret = "SECRETKEY"

# [vars]
# MY_VARIABLE = "production_value"
